# SciPy libraries for Data Analytics and Visualization

Hey everyone! Welcome to Advanced Data Analytics hosted by Gesher Group. Today we're learning about SciPy and all the libraries it contains.

# SciPy

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. With SciPy an interactive Python session becomes a data-processing and system-prototyping environment rivaling systems such as MATLAB, IDL, Octave, R-Lab, and SciLab.

The additional benefit of basing SciPy on Python is that this also makes a powerful programming language available for use in developing sophisticated programs and specialized applications. Scientific applications using SciPy benefit from the development of additional modules in numerous niches of the software landscape by developers across the world. 

Everything from parallel programming to web and data-base subroutines and classes have been made available to the Python programmer. All of this power is available in addition to the mathematical libraries in SciPy.

We'll focus a lot more on NumPy arrays, but let's show some of the capabilities of SciPy:

In [2]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Linear Algebra
**linalg**

In [3]:
from scipy import linalg

Determinant of a Matrix

In [4]:
# Compute the determinant of a matrix
linalg.det(A)

0.0

Compute pivoted LU decomposition of a matrix.

The decomposition is::

    A = P L U

where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.

In [5]:
P, L, U = linalg.lu(A)

In [6]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [7]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [8]:
U

array([[ 7.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [ 0.00000000e+00,  8.57142857e-01,  1.71428571e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.58603289e-16]])

In [9]:
np.dot(L,U)

array([[7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.]])

We can find out the eigenvalues and eigenvectors of this matrix:

In [10]:
EW, EV = linalg.eig(A)

In [11]:
EW

array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -9.75918483e-16+0.j])

In [12]:
EV

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

Solving systems of linear equations can also be done:

In [13]:
v = np.array([[2],[3],[5]])

In [14]:
v

array([[2],
       [3],
       [5]])

In [16]:
s =linalg.solve(A,v)

In [17]:
s

array([[ 3.15251974e+15],
       [-6.30503948e+15],
       [ 3.15251974e+15]])

## Sparse Linear Algebra
SciPy has some routines for computing with sparse and potentially very large matrices. The necessary tools are in the submodule scipy.sparse.

We make one example on how to construct a large matrix:

In [18]:
from scipy import sparse

In [19]:
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000, 1000))

In [20]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [21]:
A[0,:100] = np.random.rand(100)

In [22]:
A[1,100:200] = A[0,:100]

In [24]:
A.setdiag(np.random.rand(1000))

In [25]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

**Linear Algebra for Sparse Matrices**

In [26]:
from scipy.sparse import linalg

In [27]:
# Convert this matrix to Compressed Sparse Row format.
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [28]:
A = A.tocsr()

In [29]:
b = np.random.rand(1000)

In [30]:
linalg.spsolve(A, b)

array([-1.64011176e+02, -8.90247274e+01,  8.25068765e-01,  4.51261878e-01,
        5.55665216e-01,  1.43667853e+00,  9.29610275e-01,  8.94343065e+00,
        7.83467284e-01,  5.27528500e-01,  7.73871690e-01,  2.60797953e-01,
        3.08589995e-01,  6.09615727e-01,  8.29526011e+00,  1.29737134e+00,
        1.28806665e-01,  2.63999206e+00,  1.47288081e+00,  1.08321414e+00,
        1.28700609e+00,  8.04968982e-01,  5.87957886e-03,  5.07164760e-01,
        3.53741314e-01,  1.97358118e+00,  1.87297065e+00,  1.32760277e+01,
        1.62408770e+00,  2.09049013e+00,  1.35150024e-01,  4.83782812e+00,
        1.30629369e-01,  1.37618549e+00,  7.13860625e-01,  2.48336603e+00,
        4.30584350e+00,  2.67029226e-01,  7.60549919e+00,  1.67638593e+00,
        4.86336922e-01,  7.09248797e-01,  3.65530007e-02,  1.89869544e+00,
        5.88630277e+00,  2.36446101e-01,  6.39944592e-03,  1.62007811e+00,
        9.42999236e-01,  1.16287391e+00,  4.79347861e-01,  9.42224049e-01,
        3.24731965e+00,  

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

You can import NumPy as a library:

In [31]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [32]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [33]:
np.array(my_list)

array([1, 2, 3])

In [34]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [35]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [36]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [38]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.ones(3)

array([1., 1., 1.])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [42]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [43]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [45]:
np.random.rand(2)

array([0.32494952, 0.44075362])

In [46]:
np.random.rand(5,5)

array([[0.48314815, 0.53176934, 0.58782761, 0.9621088 , 0.93888978],
       [0.61388988, 0.13345193, 0.1029011 , 0.7833881 , 0.55269976],
       [0.72998451, 0.96501984, 0.48951829, 0.34797026, 0.47159807],
       [0.28272607, 0.57231574, 0.23110241, 0.70704119, 0.67699542],
       [0.15076076, 0.53016576, 0.382767  , 0.29612378, 0.56185599]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [47]:
np.random.randn(2)

array([-1.2096381 ,  1.06412294])

In [48]:
np.random.randn(5,5)

array([[ 0.20905325, -0.20649469, -1.15347815, -0.26315017,  1.83882283],
       [-0.21685855, -0.43189625, -0.12397512,  0.21273622, -0.74334919],
       [-0.1378208 , -0.15751723, -0.03108824,  0.73889699, -0.23652403],
       [-1.26337007,  1.0942907 ,  0.4280431 , -1.14348348,  1.1588491 ],
       [ 2.17885543,  1.05314302, -1.42127673, -0.51502906,  0.47046484]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [49]:
np.random.randint(1,100)

48

In [50]:
np.random.randint(1,100,10)

array([38, 41, 59, 79, 71, 48, 48, 43, 31, 88])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [51]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr

array([ 1, 20, 11, 20, 14, 41, 28, 13, 33, 32])

## Reshape
Returns an array containing the same data with a new shape.

In [55]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [56]:
ranarr

array([ 1, 20, 11, 20, 14, 41, 28, 13, 33, 32])

In [57]:
ranarr.max()

41

In [58]:
ranarr.argmax()

5

In [59]:
ranarr.min()

1

In [60]:
ranarr.argmin()

0

## Shape

Shape is an attribute that arrays have (not a method):

In [61]:
# Vector
arr.shape

(25,)

In [62]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [63]:
arr.reshape(1,25).shape

(1, 25)

In [64]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [66]:
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [67]:
import numpy as np

In [68]:
#Creating sample array
arr = np.arange(0,11)

In [69]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [70]:
#Get a value at an index
arr[8]

8

In [71]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [72]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [73]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [74]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [76]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [78]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [80]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [82]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [83]:
# Getting individual element value
arr_2d[1,0]

20

In [84]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [86]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [103]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [105]:
#Length of array
print(arr2d.shape)
arr_length = arr2d.shape[1]

(10, 10)


In [108]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [109]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [110]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [111]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [113]:
bool_arr = arr>4

In [114]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [115]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [116]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [118]:
import numpy as np
arr = np.arange(0,10)

In [119]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [120]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [121]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [122]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [123]:
# Also warning, but not an error instead infinity
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [124]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [125]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [126]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [127]:
np.max(arr) #same as arr.max()

9

In [128]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [130]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Great Job!

That's all we need to know for now!

There is a lot more that SciPy is capable of, such as Fourier Transforms, Bessel Functions, etc...

You can reference the Documentation for more details!

https://docs.scipy.org/doc/